CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS connections (id text PRIMARY KEY, provider text NOT NULL, status text NOT NULL, encrypted_token text, mailbox text, last_sync timestamptz, cursor jsonb, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE connections ADD COLUMN IF NOT EXISTS generation text NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS companies (id text PRIMARY KEY, name text NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS contacts (id text PRIMARY KEY, first_name text NOT NULL, last_name text NOT NULL, role text NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS contact_identities (contact_id text NOT NULL REFERENCES contacts(id) ON DELETE CASCADE, email text NOT NULL, PRIMARY KEY(contact_id,email));
CREATE TABLE IF NOT EXISTS deals (id text PRIMARY KEY,status text NOT NULL,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS contact_companies (contact_id text NOT NULL REFERENCES contacts(id) ON DELETE CASCADE, company_id text NOT NULL REFERENCES companies(id) ON DELETE CASCADE, PRIMARY KEY(contact_id,company_id));
CREATE TABLE IF NOT EXISTS contact_deals (contact_id text NOT NULL REFERENCES contacts(id) ON DELETE CASCADE, deal_id text NOT NULL REFERENCES deals(id) ON DELETE CASCADE, PRIMARY KEY(contact_id,deal_id));
CREATE TABLE IF NOT EXISTS threads (id text PRIMARY KEY,provider text NOT NULL,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS messages (id text PRIMARY KEY,thread_id text NOT NULL REFERENCES threads(id) ON DELETE CASCADE,position integer NOT NULL,timestamp timestamptz NOT NULL,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS participants (message_id text NOT NULL REFERENCES messages(id) ON DELETE CASCADE,role text NOT NULL,email text NOT NULL,name text NOT NULL,PRIMARY KEY(message_id,role,email));
CREATE TABLE IF NOT EXISTS segment_requests (id text PRIMARY KEY,query text NOT NULL,spec jsonb NOT NULL,assumptions jsonb NOT NULL,source text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS export_jobs (id text PRIMARY KEY,segment_id text NOT NULL REFERENCES segment_requests(id) ON DELETE CASCADE,status text NOT NULL,stage text NOT NULL,progress integer NOT NULL DEFAULT 0,attempts integer NOT NULL DEFAULT 0,lease_owner text,lease_until timestamptz,mode text NOT NULL,scenario text NOT NULL,counts jsonb NOT NULL,failures jsonb NOT NULL,exclusions jsonb NOT NULL,error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS one_export_per_segment ON export_jobs(segment_id);
CREATE INDEX IF NOT EXISTS queue_status_lease ON export_jobs(status,lease_until,created_at);
CREATE TABLE IF NOT EXISTS export_results (job_id text NOT NULL REFERENCES export_jobs(id) ON DELETE CASCADE,contact_id text NOT NULL,thread_id text NOT NULL,data jsonb NOT NULL,PRIMARY KEY(job_id,contact_id,thread_id));
CREATE TABLE IF NOT EXISTS sync_jobs (id text PRIMARY KEY,export_job_id text NOT NULL REFERENCES export_jobs(id) ON DELETE CASCADE,status text NOT NULL,cursor jsonb,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
INSERT INTO schema_migrations(version) VALUES(1) ON CONFLICT DO NOTHING;
